language: java

sudo: false

jdk:
- oraclejdk8
- openjdk7
- openjdk8

script:
- gradle test

install:
- /bin/true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0113bd5bcc59136fbc46
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
