plugins{
    id 'java'
    id 'maven-publish'
    id 'groovy'
    id 'idea'
    id 'eclipse'
    id 'signing'
}
apply from: rootDir.canonicalPath + '/.gradle/publish.gradle'
//apply plugin:'java'
//apply plugin:'maven-publish'
//apply plugin:'groovy'
//apply plugin:'idea'
//apply plugin:'eclipse'
//apply plugin:'signing'

group = "com.github"
archivesBaseName = "hyavijava"
version = '6.0.08.1'
ext.isReleaseVersion = !version.endsWith("SNAPSHOT")
targetCompatibility = 1.8
sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.directory.studio:org.dom4j.dom4j:1.6.1'
    implementation 'log4j:log4j:1.2.17'
    implementation 'org.apache.httpcomponents:httpclient:4.3.5'
    implementation 'org.projectlombok:lombok:1.18.30'
    implementation 'javax.xml.bind:jaxb-api:2.3.1'
    implementation 'org.apache.commons:commons-text:1.9'
    testImplementation 'javax.servlet:javax.servlet-api:3.1.0'
    testImplementation 'junit:junit-dep:4.11'
    testImplementation 'junit:junit:4.12'
    testImplementation 'org.spockframework:spock-core:0.7-groovy-2.0'
    testImplementation 'cglib:cglib-nodep:3.2.12'
    testImplementation 'org.objenesis:objenesis:2.1'
    testImplementation 'org.codehaus.groovy:groovy-all:2.5.23'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
}

sourceSets {

    main {
        java {
        }
    }

    intTest {
        java {
            compileClasspath += main.output + test.output
            runtimeClasspath += main.output + test.output
        }
        groovy {
            compileClasspath += main.output + test.output
            runtimeClasspath += main.output + test.output
        }
    }

    test {
        java {
        }
        groovy {
        }
    }
}

configurations {
    intTestCompile.extendsFrom testCompile
    intTestRuntime.extendsFrom testRuntime
}

task intTest(type:Test){
    description = "Run integration tests (located in src/intTest/...)."
    testClassesDirs = project.sourceSets.intTest.output.classesDirs
    classpath = project.sourceSets.intTest.runtimeClasspath
}

test {
    testLogging {
        events 'started', 'passed'
    }
}

task javadocJar(type: Jar) {
    archiveClassifier = 'javadoc'
    from javadoc
}
compileJava.options.encoding("UTF-8")
javadoc.options.encoding("UTF-8")
allprojects {
    tasks.withType(Javadoc).all {enabled =false}
}

task sourcesJar(type: Jar) {
    archiveClassifier = 'sources'
    from sourceSets.main.allSource
}

artifacts {
    archives javadocJar, sourcesJar
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = "com.github"
            artifactId = "hyavijava"
            version = "6.0.08.1"
            from components.java
            artifact sourcesJar
            artifact javadocJar
            pom {
                // 构件名称
                // 区别于artifactId，可以理解为artifactName
                name = 'hyavijava'
                // 构件描述
                description = 'Java library for VMware vSphere'
                // 构件主页
                url = 'https://github.com/hyavijava/hyavijava'
                // 许可证名称和地址
                licenses {
                    license {
                        name = 'BSD'
                        url = 'http://opensource.org/licenses/BSD-3-Clause'
                    }
                }
                // 开发者信息
                developers {
                    developer {
                        name = 'hyavijava'
                        email = 'hyavijava@163.com'
                    }
                }
                // 版本控制仓库地址
                scm {
                    url = 'https://github.com/hyavijava/hyavijava'
                    connection = 'scm:git:https://github.com/hyavijava/hyavijava.git'
                    developerConnection = 'scm:git:https://github.com/hyavijava/hyavijava.git'
                }
            }
        }
    }
    repositories {
        maven {
            url "https://oss.sonatype.org/service/local/staging/deploy/maven2"
            credentials {
                username sonatypeUsername
                password sonatypePassword
            }
        }
    }
}

signing {
    sign publishing.publications.mavenJava
}
