package com.vmware.vim25;

/**
 * Created by Michael Rice on Fri Apr 24 22:47:38 CDT 2026
 * This code is auto generated using yavijava_generator
 * https://github.com/yavijava/yavijava_generator
 *
 * Copyright 2015 Michael Rice
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * @since 6.0
 */

public enum VirtualMachineGuestOsIdentifier {

    dosGuest("dosGuest"),
    win31Guest("win31Guest"),
    win95Guest("win95Guest"),
    win98Guest("win98Guest"),
    winMeGuest("winMeGuest"),
    winNTGuest("winNTGuest"),
    win2000ProGuest("win2000ProGuest"),
    win2000ServGuest("win2000ServGuest"),
    win2000AdvServGuest("win2000AdvServGuest"),
    winXPHomeGuest("winXPHomeGuest"),
    winXPProGuest("winXPProGuest"),
    winXPPro64Guest("winXPPro64Guest"),
    winNetWebGuest("winNetWebGuest"),
    winNetStandardGuest("winNetStandardGuest"),
    winNetEnterpriseGuest("winNetEnterpriseGuest"),
    winNetDatacenterGuest("winNetDatacenterGuest"),
    winNetBusinessGuest("winNetBusinessGuest"),
    winNetStandard64Guest("winNetStandard64Guest"),
    winNetEnterprise64Guest("winNetEnterprise64Guest"),
    winLonghornGuest("winLonghornGuest"),
    winLonghorn64Guest("winLonghorn64Guest"),
    winNetDatacenter64Guest("winNetDatacenter64Guest"),
    winVistaGuest("winVistaGuest"),
    winVista64Guest("winVista64Guest"),
    windows7Guest("windows7Guest"),
    windows7_64Guest("windows7_64Guest"),
    windows7Server64Guest("windows7Server64Guest"),
    windows8Guest("windows8Guest"),
    windows8_64Guest("windows8_64Guest"),
    windows8Server64Guest("windows8Server64Guest"),
    windows9Guest("windows9Guest"),
    windows9_64Guest("windows9_64Guest"),
    windows9Server64Guest("windows9Server64Guest"),
    windows11_64Guest("windows11_64Guest"),
    windows12_64Guest("windows12_64Guest"),
    windowsHyperVGuest("windowsHyperVGuest"),
    windows2019srv_64Guest("windows2019srv_64Guest"),
    windows2019srvNext_64Guest("windows2019srvNext_64Guest"),
    windows2022srvNext_64Guest("windows2022srvNext_64Guest"),
    freebsdGuest("freebsdGuest"),
    freebsd64Guest("freebsd64Guest"),
    freebsd11Guest("freebsd11Guest"),
    freebsd11_64Guest("freebsd11_64Guest"),
    freebsd12Guest("freebsd12Guest"),
    freebsd12_64Guest("freebsd12_64Guest"),
    freebsd13Guest("freebsd13Guest"),
    freebsd13_64Guest("freebsd13_64Guest"),
    freebsd14Guest("freebsd14Guest"),
    freebsd14_64Guest("freebsd14_64Guest"),
    freebsd15Guest("freebsd15Guest"),
    freebsd15_64Guest("freebsd15_64Guest"),
    redhatGuest("redhatGuest"),
    rhel2Guest("rhel2Guest"),
    rhel3Guest("rhel3Guest"),
    rhel3_64Guest("rhel3_64Guest"),
    rhel4Guest("rhel4Guest"),
    rhel4_64Guest("rhel4_64Guest"),
    rhel5Guest("rhel5Guest"),
    rhel5_64Guest("rhel5_64Guest"),
    rhel6Guest("rhel6Guest"),
    rhel6_64Guest("rhel6_64Guest"),
    rhel7Guest("rhel7Guest"),
    rhel7_64Guest("rhel7_64Guest"),
    rhel8_64Guest("rhel8_64Guest"),
    rhel9_64Guest("rhel9_64Guest"),
    rhel10_64Guest("rhel10_64Guest"),
    centosGuest("centosGuest"),
    centos64Guest("centos64Guest"),
    centos6Guest("centos6Guest"),
    centos6_64Guest("centos6_64Guest"),
    centos7Guest("centos7Guest"),
    centos7_64Guest("centos7_64Guest"),
    centos8_64Guest("centos8_64Guest"),
    centos9_64Guest("centos9_64Guest"),
    oracleLinuxGuest("oracleLinuxGuest"),
    oracleLinux64Guest("oracleLinux64Guest"),
    oracleLinux6Guest("oracleLinux6Guest"),
    oracleLinux6_64Guest("oracleLinux6_64Guest"),
    oracleLinux7Guest("oracleLinux7Guest"),
    oracleLinux7_64Guest("oracleLinux7_64Guest"),
    oracleLinux8_64Guest("oracleLinux8_64Guest"),
    oracleLinux9_64Guest("oracleLinux9_64Guest"),
    oracleLinux10_64Guest("oracleLinux10_64Guest"),
    suseGuest("suseGuest"),
    suse64Guest("suse64Guest"),
    slesGuest("slesGuest"),
    sles64Guest("sles64Guest"),
    sles10Guest("sles10Guest"),
    sles10_64Guest("sles10_64Guest"),
    sles11Guest("sles11Guest"),
    sles11_64Guest("sles11_64Guest"),
    sles12Guest("sles12Guest"),
    sles12_64Guest("sles12_64Guest"),
    sles15_64Guest("sles15_64Guest"),
    sles16_64Guest("sles16_64Guest"),
    nld9Guest("nld9Guest"),
    oesGuest("oesGuest"),
    sjdsGuest("sjdsGuest"),
    mandrakeGuest("mandrakeGuest"),
    mandrivaGuest("mandrivaGuest"),
    mandriva64Guest("mandriva64Guest"),
    turboLinuxGuest("turboLinuxGuest"),
    turboLinux64Guest("turboLinux64Guest"),
    ubuntuGuest("ubuntuGuest"),
    ubuntu64Guest("ubuntu64Guest"),
    debian4Guest("debian4Guest"),
    debian4_64Guest("debian4_64Guest"),
    debian5Guest("debian5Guest"),
    debian5_64Guest("debian5_64Guest"),
    debian6Guest("debian6Guest"),
    debian6_64Guest("debian6_64Guest"),
    debian7Guest("debian7Guest"),
    debian7_64Guest("debian7_64Guest"),
    debian8Guest("debian8Guest"),
    debian8_64Guest("debian8_64Guest"),
    debian9Guest("debian9Guest"),
    debian9_64Guest("debian9_64Guest"),
    debian10Guest("debian10Guest"),
    debian10_64Guest("debian10_64Guest"),
    debian11Guest("debian11Guest"),
    debian11_64Guest("debian11_64Guest"),
    debian12Guest("debian12Guest"),
    debian12_64Guest("debian12_64Guest"),
    debian13Guest("debian13Guest"),
    debian13_64Guest("debian13_64Guest"),
    asianux3Guest("asianux3Guest"),
    asianux3_64Guest("asianux3_64Guest"),
    asianux4Guest("asianux4Guest"),
    asianux4_64Guest("asianux4_64Guest"),
    asianux5_64Guest("asianux5_64Guest"),
    asianux7_64Guest("asianux7_64Guest"),
    asianux8_64Guest("asianux8_64Guest"),
    asianux9_64Guest("asianux9_64Guest"),
    miraclelinux_64Guest("miraclelinux_64Guest"),
    pardus_64Guest("pardus_64Guest"),
    opensuseGuest("opensuseGuest"),
    opensuse64Guest("opensuse64Guest"),
    fedoraGuest("fedoraGuest"),
    fedora64Guest("fedora64Guest"),
    coreos64Guest("coreos64Guest"),
    vmwarePhoton64Guest("vmwarePhoton64Guest"),
    other24xLinuxGuest("other24xLinuxGuest"),
    other26xLinuxGuest("other26xLinuxGuest"),
    otherLinuxGuest("otherLinuxGuest"),
    other3xLinuxGuest("other3xLinuxGuest"),
    other4xLinuxGuest("other4xLinuxGuest"),
    other5xLinuxGuest("other5xLinuxGuest"),
    other6xLinuxGuest("other6xLinuxGuest"),
    other7xLinuxGuest("other7xLinuxGuest"),
    genericLinuxGuest("genericLinuxGuest"),
    other24xLinux64Guest("other24xLinux64Guest"),
    other26xLinux64Guest("other26xLinux64Guest"),
    other3xLinux64Guest("other3xLinux64Guest"),
    other4xLinux64Guest("other4xLinux64Guest"),
    other5xLinux64Guest("other5xLinux64Guest"),
    other6xLinux64Guest("other6xLinux64Guest"),
    other7xLinux64Guest("other7xLinux64Guest"),
    otherLinux64Guest("otherLinux64Guest"),
    solaris6Guest("solaris6Guest"),
    solaris7Guest("solaris7Guest"),
    solaris8Guest("solaris8Guest"),
    solaris9Guest("solaris9Guest"),
    solaris10Guest("solaris10Guest"),
    solaris10_64Guest("solaris10_64Guest"),
    solaris11_64Guest("solaris11_64Guest"),
    fusionos_64Guest("fusionos_64Guest"),
    prolinux_64Guest("prolinux_64Guest"),
    kylinlinux_64Guest("kylinlinux_64Guest"),
    os2Guest("os2Guest"),
    eComStationGuest("eComStationGuest"),
    eComStation2Guest("eComStation2Guest"),
    netware4Guest("netware4Guest"),
    netware5Guest("netware5Guest"),
    netware6Guest("netware6Guest"),
    openServer5Guest("openServer5Guest"),
    openServer6Guest("openServer6Guest"),
    unixWare7Guest("unixWare7Guest"),
    darwinGuest("darwinGuest"),
    darwin64Guest("darwin64Guest"),
    darwin10Guest("darwin10Guest"),
    darwin10_64Guest("darwin10_64Guest"),
    darwin11Guest("darwin11Guest"),
    darwin11_64Guest("darwin11_64Guest"),
    darwin12_64Guest("darwin12_64Guest"),
    darwin13_64Guest("darwin13_64Guest"),
    darwin14_64Guest("darwin14_64Guest"),
    darwin15_64Guest("darwin15_64Guest"),
    darwin16_64Guest("darwin16_64Guest"),
    darwin17_64Guest("darwin17_64Guest"),
    darwin18_64Guest("darwin18_64Guest"),
    darwin19_64Guest("darwin19_64Guest"),
    darwin20_64Guest("darwin20_64Guest"),
    darwin21_64Guest("darwin21_64Guest"),
    darwin22_64Guest("darwin22_64Guest"),
    darwin23_64Guest("darwin23_64Guest"),
    vmkernelGuest("vmkernelGuest"),
    vmkernel5Guest("vmkernel5Guest"),
    vmkernel6Guest("vmkernel6Guest"),
    vmkernel65Guest("vmkernel65Guest"),
    vmkernel7Guest("vmkernel7Guest"),
    vmkernel8Guest("vmkernel8Guest"),
    vmkernel9Guest("vmkernel9Guest"),
    amazonlinux2_64Guest("amazonlinux2_64Guest"),
    amazonlinux3_64Guest("amazonlinux3_64Guest"),
    crxPod1Guest("crxPod1Guest"),
    crxSys1Guest("crxSys1Guest"),
    rockylinux_64Guest("rockylinux_64Guest"),
    almalinux_64Guest("almalinux_64Guest"),
    otherGuest("otherGuest"),
    otherGuest64("otherGuest64");

    private String val;

    VirtualMachineGuestOsIdentifier(String val) {
        this.val = val;
    }

    @Override
    public String toString() {
        return this.val;
    }
}
